// Executed only by the isolated verification project generated by prepare_battler_runtime.cjs.
var _results = [];
var _assert = function(_condition, _message)
{
	if (!_condition) throw _message;
};
try
{
	var _controller = instance_find(o_game_controller, 0);
	_assert(instance_exists(_controller), "Missing controller");
	_assert(_controller.battle_phase == BATTLE_PHASE.PREPARATION, "Preparation did not initialize");
	_assert(global.squad_limit == 6 && array_length(global.squads) == 3, "Starting roster or slot cap");
	_assert(array_length(global.cannon_projectile_queue) == 3, "Preparation ammunition");
	_assert(!instance_exists(o_jobs_ui) && !instance_exists(o_tutorial_controller), "Legacy campaign UI leaked");
	var _grid = instance_find(o_corruption_grid, 0);
	_assert(ds_grid_get(_grid.corruption_grid, 12, 0) == 1, "Taint top edge");
	_assert(ds_grid_get(_grid.corruption_grid, 12, _grid.grid_height - 1) == 1, "Taint bottom edge");
	_assert(ds_grid_get(_grid.corruption_grid, 13, 15) == 0, "Taint crosses 1300 pixels");
	array_push(_results, "PASS: preparation, 6 slots, 3 squads, 3 shells, exact 1300px strip");

	// Exercise the actual cannon Step event, including queue consumption and shell creation.
	var _cannon = instance_find(o_cannon, 0);
	for (var _shot = 0; _shot < BALANCE_BATTLE_TAINT_SHOTS; ++_shot)
	{
		_cannon.cannon_reload_timer = 0;
		global.cannon_target_exists = true;
		global.cannon_target_x = 1250;
		global.cannon_target_y = 1200;
		global.cannon_target_projectile_type = PROJECTILE_TYPE.CORRUPTION;
		global.cannon_target_projectile_queue_index = 0;
		global.cannon_target_consumes_projectile_queue = true;
		global.cannon_target_version++;
		with (_cannon) event_perform(ev_step, 0);
		_assert(array_length(global.cannon_projectile_queue) == BALANCE_BATTLE_TAINT_SHOTS - _shot - 1, "Taint shot did not consume exactly one charge");
	}
	_assert(instance_number(o_projectile) > 0, "Cannon did not create projectiles");
	with (o_projectile) instance_destroy();
	array_push(_results, "PASS: three cannon shots consume all three preparation charges");

	var _squad = global.squads[0];
	var _positions = battle_formation_positions_get(_squad, 825, 1200);
	_assert(battle_deployment_is_valid(_controller, _squad, _positions), "Valid deployment rejected");
	_assert(battle_squad_deploy(_controller, _squad, _positions), "Deployment failed");
	_assert(array_length(_squad.units) == 10 && _controller.battle_deployed_count == 1, "Duplicate or missing deployed units");
	var _unit = _squad.units[0];
	var _original_x = _unit.x;
	with (_unit) event_perform(ev_step, 0);
	_assert(_unit.x == _original_x, "Friendly unit moved in preparation");
	_assert(!battle_squad_deploy(_controller, _squad, battle_formation_positions_get(_squad, 1300, 1200)), "Formation straddles Taint edge");
	_assert(_unit.x == _original_x && _controller.battle_deployed_count == 1, "Invalid drop changed deployed squad");
	_assert(!battle_squad_deploy(_controller, global.squads[1], _positions), "Overlapping squads accepted");
	_assert(!battle_deployment_is_valid(_controller, _squad, battle_formation_positions_get(_squad, 0, 0)), "Room-edge placement accepted");
	_assert(battle_squad_recall(_controller, _squad), "Recall failed");
	_assert(_controller.battle_deployed_count == 0 && !instance_exists(_unit), "Recall left units behind");
	_controller.battle_deployed_count = 4;
	_assert(!battle_squad_deploy(_controller, _squad, _positions), "Fifth squad accepted");
	_controller.battle_deployed_count = 0;
	_assert(battle_squad_deploy(_controller, _squad, _positions), "Redeployment failed");
	array_push(_results, "PASS: deployment, preparation freeze, invalid drops, overlap, recall, four-squad cap");

	_assert(battle_enemy_zone_get(3500, 5000) == BATTLE_ZONE.FIRST_ATTACK, "First zone boundary");
	_assert(battle_enemy_zone_get(3999, 5000) == BATTLE_ZONE.FIRST_ATTACK, "First zone right boundary");
	_assert(battle_enemy_zone_get(4000, 5000) == BATTLE_ZONE.SECOND_ATTACK, "Second zone boundary");
	_assert(battle_enemy_zone_get(4499, 5000) == BATTLE_ZONE.SECOND_ATTACK, "Second zone right boundary");
	_assert(battle_enemy_zone_get(4500, 5000) == BATTLE_ZONE.DEFENSE, "Defensive zone boundary");
	var _first = instance_create_layer(3550, 1200, "Instances", o_enemy_peasant);
	var _second = instance_create_layer(4150, 1200, "Instances", o_enemy_archer);
	var _defender = instance_create_layer(4650, 1500, "Instances", o_enemy_knight);
	var _helper = instance_create_layer(4700, 1750, "Instances", o_enemy_peasant);
	battle_enemy_prepare(_first, _controller);
	battle_enemy_prepare(_second, _controller);
	battle_enemy_prepare(_defender, _controller);
	battle_enemy_prepare(_helper, _controller);
	with (_first) event_perform(ev_step, 0);
	_assert(_first.x == 3550 && !_first.unit_can_attack_cannon, "Enemy moved during preparation");
	_assert(battle_start(_controller), "Battle start failed");
	_assert(_squad.properties.battle_deployed && !_squad.units[0].cannon_loaded, "Night start swallowed squad");
	_assert(_controller.cannon_projectile_queue_type_count_get(PROJECTILE_TYPE.CORRUPTION) == 0, "Taint shells survived preparation");
	_assert(_controller.cannon_projectile_queue_type_count_get(PROJECTILE_TYPE.BOMB) == 1, "Missing night cannon shells");
	_controller.battle_elapsed_seconds = 4.9;
	with (_first) event_perform(ev_step, 0);
	_assert(!_first.unit_can_attack_cannon, "First wave released early");
	_controller.battle_elapsed_seconds = 5;
	with (_first) event_perform(ev_step, 0);
	_assert(_first.unit_can_attack_cannon && _first.x < 3550, "First wave did not attack left at 5s");
	_controller.battle_elapsed_seconds = 14.9;
	with (_second) event_perform(ev_step, 0);
	_assert(!_second.unit_can_attack_cannon, "Second wave released early");
	_controller.battle_elapsed_seconds = 15;
	with (_second) event_perform(ev_step, 0);
	_assert(_second.unit_can_attack_cannon && _second.x < 4150, "Second wave did not attack left at 15s");
	with (_defender) event_perform(ev_step, 0);
	_assert(!_defender.unit_can_attack_cannon && _defender.x == 4650, "Defender left its position without a threat");
	_assert(!_defender.target_can_be_attacked(instance_find(o_cannon, 0)), "Defender can target cannon");
	array_push(_results, "PASS: zone boundaries, 5s/15s release, leftward attacks, squads stay deployed, night cannon");

	var _intruder = instance_create_layer(4580, 1520, "Instances", o_skeleton);
	battle_enemy_target_update(_defender);
	_assert(_defender.target_instance == _intruder && _helper.alert_target == _intruder, "Spotting did not call nearby help");
	_intruder.x = 3000;
	battle_enemy_target_update(_defender);
	_assert(_defender.target_instance == noone, "Defender chased beyond its leash");
	_defender.x = 4600;
	with (_defender) event_perform(ev_step, 0);
	_assert(_defender.x > 4600, "Defender did not return to its position");
	battle_result_update(_controller);
	_assert(_controller.battle_phase == BATTLE_PHASE.BATTLE, "Battle won while enemies remained");
	with (o_units_parent)
	{
		if (unit_faction == UNIT_FACTION.ENEMY) hp = 0;
	}
	battle_result_update(_controller);
	_assert(_controller.battle_phase == BATTLE_PHASE.VICTORY && global.pause, "Victory did not freeze simulation");
	_controller.battle_phase = BATTLE_PHASE.BATTLE;
	var _cannon = instance_find(o_cannon, 0);
	_cannon.hp = 0;
	battle_result_update(_controller);
	_assert(_controller.battle_phase == BATTLE_PHASE.DEFEAT, "Cannon defeat did not resolve");
	array_push(_results, "PASS: defensive assistance, leash, return home, all-enemy victory, cannon defeat");
}
catch (_error)
{
	array_push(_results, "FAIL: " + string(_error));
}

// Save a machine-readable result outside the production project and exit the test runner.
var _file = file_text_open_write("battler_verification.txt");
var _count = array_length(_results);
for (var _index = 0; _index < _count; ++_index)
{
	file_text_write_string(_file, _results[_index]);
	file_text_writeln(_file);
	show_debug_message(_results[_index]);
}
file_text_close(_file);
game_end();
