/// @description Project-wide enums and macros.

enum PROJECTILE_TYPE
{
	DAMAGE,
	CORRUPTION,
	SUMMON
}

enum FOCUS_WINDOW
{
	NOONE,
	TARGET_SELECTION,
	PAUSE_MENU,
	SETTINGS
}

enum RESOURCES
{
	SOULS,
	IRON,
	CULTISTS,
	COUNT
}

enum UNIT_FACTION
{
	NOONE,
	FRIENDLY,
	ENEMY
}

enum DAY_PHASE
{
	DAY,
	NIGHT
}

#macro COLOR_PROJECTILE_DAMAGE $ff4a42
#macro COLOR_PROJECTILE_CORRUPTION $b45cff
#macro COLOR_PROJECTILE_SUMMON $48d982
#macro COLOR_PROJECTILE_PREVIEW $ffffff
#macro COLOR_PARTICLE_SMOKE $5f5c58
#macro COLOR_PARTICLE_EXPLOSION_INNER $ffe47c
#macro COLOR_PARTICLE_EXPLOSION_OUTER $ff5c2e
#macro COLOR_HUD_TEXT $ffffff
#macro COLOR_HUD_BACKGROUND $101216
#macro COLOR_HUD_PROJECTILE_SELECTED $ffffff
#macro COLOR_HUD_PROJECTILE_DESCRIPTION $d8dde6
#macro COLOR_HUD_SOULS $b45cff
#macro COLOR_HUD_IRON $a6adb4
#macro COLOR_HUD_CULTISTS $f0d27a
#macro COLOR_HUD_CORRUPTION $6c238f
#macro COLOR_CORRUPTION_MAX $6c238f
#macro COLOR_HOLY_GROUND $f2d76b
#macro COLOR_HOLY_TOWER_RADIUS $f2d76b
#macro COLOR_HEALTH_BAR $48d982
#macro COLOR_NIGHT_OVERLAY $1b1433
