/// @description Project-wide enums and macros.

enum PROJECTILE_TYPE
{
	DAMAGE,
	CORRUPTION,
	SUMMON,
	RALLY,
	CULTIST,
	FEAST,
	HEAL,
	BOMB,
	SKELETONS,
	BUILDING_SHELL,
	CLEANSE,
	ARTILLERY,
	DOOM_BELL,
	COUNT
}

enum FOCUS_WINDOW
{
	NOONE,
	TARGET_SELECTION,
	PAUSE_MENU,
	SETTINGS,
	CULTIST_DEMON_SELECTION,
	CULTIST_LEVEL_UP,
	BUILDING_CONSTRUCTION,
	BUILDING_UPGRADE,
	BUILDING_EVENTS,
	CURSED_POINT_STRUCTURE_SELECTION,
	JOBS,
	END_DAY_CONFIRMATION,
	WORLD_EVENT_SQUAD_SELECTION,
	BLOOD_MOON_REWARD,
	EARLY_UPGRADE_SELECTION,
	GAME_COMPLETION,
	CANNON_SATISFACTION
}

enum CANNON_SATISFACTION_LEVEL
{
	SULKING,
	AWAKE,
	PLAYFUL,
	ECSTATIC,
	IT_MUST_FIRE
}

enum EARLY_UPGRADE_CHOICE
{
	COPY_SQUAD,
	BONELET_RESURRECTION,
	DOUBLE_SHELL_PRODUCTION,
	COUNT
}

enum DAYBREAK_UPGRADE_SET
{
	DAY_TWO,
	DAY_THREE
}

enum DAY_THREE_UPGRADE_CHOICE
{
	DOUBLE_TOWER_RADIUS,
	TAINTED_GROUND_HEALING,
	DEATH_EXPLOSION,
	COUNT
}

enum RESOURCES
{
	FLESH,
	SOULS,
	IRON,
	IHOR,
	COUNT
}

enum UNIT_FACTION
{
	NOONE,
	FRIENDLY,
	ENEMY
}

enum DAY_PHASE
{
	DAY,
	NIGHT
}

enum SQUAD_TYPE
{
	ARCHDEMON,
	UNDEAD,
	DEMON,
	COUNT
}

enum CANNON_UPGRADE
{
	SETTLEMENT_EXPANSION,
	CORRUPTED_GROUND_DAMAGE,
	MORNING_SKELETONS,
	PAYLOAD_MASTERY,
	COUNT
}

enum CULTIST_STAT
{
	BODY,
	SPIRIT,
	FERVOR,
	COUNT
}

enum CULTIST_LEVEL_REWARD
{
	ATTRIBUTE,
	PASSIVE,
	ACTIVE,
	ABILITY_UPGRADE
}

enum DEMON_TYPE
{
	NONE,
	IMP,
	WARLOCK,
	BRUTE
}

enum DEMON_ABILITY
{
	NONE,
	IMP_BLOOD_BLADES,
	IMP_FRENZY_ECHO,
	IMP_BLOOD_HUNGER,
	IMP_DEMON_LEAP,
	IMP_CRIMSON_GUILLOTINE,
	IMP_BLOODY_CLONE,
	BRUTE_CORPSE_EATER,
	BRUTE_ROTTEN_AURA,
	BRUTE_BLOOD_ANVIL,
	BRUTE_GRAVE_SLAM,
	BRUTE_BUTCHER_CHAINS,
	BRUTE_CORPSE_ARMOR,
	WARLOCK_SOUL_ENGINE,
	WARLOCK_FAMILIAR,
	WARLOCK_DEMONIC_INFUSION,
	WARLOCK_RAISE_LESSER_DEMON,
	WARLOCK_SOUL_CHAIN,
	WARLOCK_HEX_TOTEM,
	COUNT
}

enum STATUS_EFFECT
{
	BLEED,
	FEAR,
	SOUL_MARK,
	CURSE,
	STUN,
	COUNT
}

// Temporary feature switch for Taint spreading from newly infected trees.
#macro TREE_CORRUPTION_SPREAD_ENABLED false

// GUI draw order keeps Jobs above gameplay indicators within GameMaker's valid depth range.
#macro DEPTH_JOBS_UI -15000
#macro DEPTH_TUTORIAL_UI -15900

#macro COLOR_PROJECTILE_DAMAGE $ff4a42
#macro COLOR_PROJECTILE_CORRUPTION #3E3631
#macro COLOR_PROJECTILE_SUMMON $48d982
#macro COLOR_PROJECTILE_RALLY #58a6ff
#macro COLOR_PROJECTILE_CULTIST #b45cff
#macro COLOR_PROJECTILE_HEAL #48ff82
#macro COLOR_PROJECTILE_BOMB #ff9b2f
#macro COLOR_PROJECTILE_SKELETONS #d8dde6
#macro COLOR_PROJECTILE_BUILDING_SHELL #f2d76b
#macro COLOR_PROJECTILE_CLEANSE #f2d76b
#macro COLOR_PROJECTILE_PREVIEW $ffffff
#macro COLOR_PARTICLE_SMOKE $5f5c58
#macro COLOR_PARTICLE_EXPLOSION_INNER $ffe47c
#macro COLOR_PARTICLE_EXPLOSION_OUTER $ff5c2e
#macro COLOR_STATUS_NEGATIVE_RED #ff1f2d
#macro COLOR_STATUS_SOUL_MARK $6AF37A
#macro COLOR_STATUS_CURSE $b45cff
#macro COLOR_SUPPORT_BUFF $b45cff
#macro COLOR_SUPPORT_HEAL $48ff82
#macro COLOR_BRUTE_ROTTEN_AURA $6AF37A
#macro COLOR_BRUTE_GRAVE_SLAM $5f5c58
#macro COLOR_BRUTE_MEAT_EXPLOSION $ff1f2d
#macro COLOR_BRUTE_HOOK_LINE $111111
#macro COLOR_WARLOCK_DEMONIC_INFUSION $b45cff
#macro COLOR_WARLOCK_SOUL_ENGINE $8f7cff
#macro COLOR_WARLOCK_FAMILIAR $8f7cff
#macro COLOR_WARLOCK_SUMMON_SKELETONS $6AF37A
#macro COLOR_WARLOCK_SOUL_CHAIN $b45cff
#macro COLOR_WARLOCK_HEX_TOTEM $b45cff
#macro COLOR_HUD_TEXT $ffffff
#macro COLOR_HUD_BACKGROUND $101216
#macro COLOR_JOBS_WINDOW_BACKGROUND #171412
#macro COLOR_JOBS_POOL_BORDER #573E31
#macro COLOR_JOBS_EVENT_INACTIVE #2D211B
#macro COLOR_JOBS_EVENT_ACTIVE #573E31
#macro COLOR_JOBS_REROLL_PREVIEW #9E7D3E
#macro COLOR_JOBS_SLOT_BORDER #896C50
#macro COLOR_JOBS_END_DAY #4B100C
#macro COLOR_JOBS_ASSIGN_BACKGROUND #480f0c
#macro COLOR_JOBS_ASSIGN_BORDER #831c17
#macro COLOR_JOBS_ASSIGN_TEXT #e9d3b0
#macro COLOR_JOBS_EVENT_ACTION #ff0000
#macro COLOR_CANNON_SATISFACTION_ACTIVE #FF0205
#macro COLOR_HUD_SIDEBAR #302823
#macro COLOR_HUD_PROJECTILE_SELECTED $ffffff
#macro COLOR_HUD_PROJECTILE_DESCRIPTION $d8dde6
#macro COLOR_HUD_FLESH #ff4a42
#macro COLOR_HUD_SOULS #6AF37A
#macro COLOR_HUD_IRON #1148FF
#macro COLOR_HUD_IHOR #9be7ff
#macro COLOR_HUD_CORRUPTION #3E3631
#macro COLOR_HUD_DAY_PROGRESS #FF0000
#macro COLOR_SQUAD_CARD_BACKGROUND #26211e
#macro COLOR_SQUAD_CARD_BORDER #665446
#macro COLOR_SQUAD_CARD_TEXT #b19f88
#macro COLOR_SQUAD_CARD_TYPE #a08f7a
#macro COLOR_CULTIST_COUNTER_TEXT #e9d3b0
#macro COLOR_SQUAD_HP_BACKGROUND #19120d
#macro COLOR_SQUAD_HP_BORDER #3c2e25
#macro COLOR_SQUAD_HP_FILL #c80002
#macro COLOR_CANNON_HP_BAR #ff0004
#macro COLOR_PHASE_BANNER_DAY #f2d76b
#macro COLOR_PHASE_BANNER_NIGHT #8f7cff
#macro COLOR_HUD_CULTIST_STATUS_HP #00ff1a
#macro COLOR_HUD_CULTIST_STATUS_EXP #2eb2ff
#macro COLOR_HUD_CULTIST_STATUS_STAMINA #ffcc3d
#macro COLOR_HUD_LEVEL_UP #ffcc3d
#macro COLOR_HUD_LEVEL_UP_HOVER #ffe36b
#macro COLOR_HUD_MINIMAP_BACKGROUND $000000
#macro COLOR_HUD_MINIMAP_TAINT #3B0000
#macro COLOR_HUD_MINIMAP_SAINT #887938
#macro COLOR_HUD_MINIMAP_ENEMY #ff0000
#macro COLOR_HUD_MINIMAP_VIEW_FILL #d9d9d9
#macro COLOR_HUD_MINIMAP_VIEW_BORDER $ffffff
#macro COLOR_HUD_MINIMAP_HEALTH_BACKGROUND #303030
#macro COLOR_CORRUPTION_MAX #3E3631
#macro COLOR_SAINT_MAX #887938
#macro COLOR_HOLY_TOWER_RADIUS $f2d76b
#macro COLOR_TOWER_CORRUPTION_RADIUS #3E3631
#macro COLOR_TOWER_DAMAGE_RADIUS #ff4a42
#macro COLOR_TOWER_HEAL_RADIUS #48d982
#macro COLOR_TOWER_VISION_RADIUS #58a6ff
#macro COLOR_ORCS_HUT_RADIUS #3E3631
#macro COLOR_IHOR_EXTRACTOR_RADIUS #9be7ff
#macro COLOR_CAPTURED_BUILDING_RIFT #FF0000
#macro COLOR_HEALTH_BAR $48d982
#macro COLOR_NIGHT_OVERLAY $1b1433
#macro COLOR_ATTACK_WARNING_UNIT_BACKGROUND #D9D9D9
#macro COLOR_CULTIST_BODY #ff4a42
#macro COLOR_CULTIST_SPIRIT #58a6ff
#macro COLOR_CULTIST_FERVOR #b45cff
#macro COLOR_CULTIST_SELECTION_BACKGROUND #2b2f27
#macro COLOR_CULTIST_SELECTION_BODY #ff0000
#macro COLOR_CULTIST_SELECTION_BRUTE #cf0000
#macro COLOR_CULTIST_SELECTION_IMP #ff00ea
#macro COLOR_CULTIST_SELECTION_WARLOCK #1c85da
#macro COLOR_CULTIST_SELECTION_RECOMMENDED #888888
#macro COLOR_ABILITY_BAR $58a6ff
#macro COLOR_DAMAGE_FRIENDLY #ff3f3f
#macro COLOR_DAMAGE_ENEMY #ff9b2f
#macro COLOR_HEAL_POPUP #48ff82
#macro COLOR_PARTICLE_HEAL #48ff82
#macro COLOR_PARTICLE_BLOOD #ff1f2d
#macro COLOR_IMP_FRENZY_AURA #b45cff
#macro COLOR_PARTICLE_FRENZY #ff3f8f
#macro COLOR_IMP_BLOOD_RAGE_AURA #ff1f2d
#macro COLOR_PARTICLE_BLOOD_RAGE #ff4a42
#macro COLOR_IMP_BLOOD_FRENZY #58a6ff
#macro COLOR_COOLDOWN_IMP_DEMON_LEAP #00c8ff
#macro COLOR_COOLDOWN_IMP_CRIMSON_GUILLOTINE #ff3048
#macro COLOR_COOLDOWN_IMP_BLOODY_CLONE #ff42ff
#macro COLOR_COOLDOWN_BRUTE_GRAVE_SLAM #8f7cff
#macro COLOR_COOLDOWN_BRUTE_BUTCHER_CHAINS #00f0ff
#macro COLOR_COOLDOWN_BRUTE_CORPSE_ARMOR #ff4a42
#macro COLOR_COOLDOWN_WARLOCK_RAISE_LESSER_DEMON #7dff5a
#macro COLOR_COOLDOWN_WARLOCK_SOUL_CHAIN #d96cff
#macro COLOR_COOLDOWN_WARLOCK_HEX_TOTEM #ff4dff
#macro COLOR_ABILITY_POPUP #ffd45a
#macro COLOR_BALANCE_TEST_BACKGROUND #14161c
#macro COLOR_BALANCE_TEST_HEADER #303440
#macro COLOR_BALANCE_TEST_ROW #22252e
#macro COLOR_BALANCE_TEST_ROW_ALTERNATE #282b35
#macro COLOR_BALANCE_TEST_MUTED_TEXT #7d8291
#macro COLOR_BALANCE_TEST_PLAYER_WIN #78e696
#macro COLOR_BALANCE_TEST_ENEMY_WIN #f08278
#macro COLOR_BALANCE_TEST_NEUTRAL #d2d2dc
