/// @description Balance constants used across gameplay systems.

#macro BALANCE_GRID_CELL_SIZE 100
#macro BALANCE_CORRUPTION_NEIGHBOR_SPREAD_PER_SECOND 0.05
#macro BALANCE_CORRUPTION_NEIGHBOR_SPREAD_UPDATE_INTERVAL 10
#macro BALANCE_FOG_REVEAL_RADIUS_IN_CELLS 4
#macro BALANCE_FOG_UPDATE_INTERVAL 10

#macro BALANCE_CANNON_VOLLEY_PROJECTILE_COUNT 4
#macro BALANCE_CANNON_VOLLEY_SPREAD_RADIUS 200
#macro BALANCE_CANNON_VOLLEY_LAUNCH_DELAY_MIN 0
#macro BALANCE_CANNON_VOLLEY_LAUNCH_DELAY_MAX 0.35
#macro BALANCE_PROJECTILE_EFFECT_RADIUS 200
#macro BALANCE_PROJECTILE_DAMAGE_AMOUNT 10
#macro BALANCE_PROJECTILE_GROUND_CORRUPTION_AMOUNT 0.34
#macro BALANCE_PROJECTILE_SPEED 520
#macro BALANCE_PROJECTILE_MIN_FLIGHT_TIME 0.55
#macro BALANCE_PROJECTILE_MAX_FLIGHT_TIME 2.4

#macro BALANCE_HOLY_TOWER_SHOOT_RADIUS 420
#macro BALANCE_HOLY_TOWER_HOLY_RADIUS_IN_CELLS 4
#macro BALANCE_HOLY_TOWER_DAMAGE 3
#macro BALANCE_HOLY_TOWER_RELOAD_TIME 1
#macro BALANCE_HOLY_TOWER_DEATH_CORRUPTION_AMOUNT 1
#macro BALANCE_HOLY_TOWER_ATTACK_FEEDBACK_TIME 0.16

#macro BALANCE_UNIT_VISION_RADIUS 250
#macro BALANCE_UNIT_ASSIST_CALL_RADIUS 280
#macro BALANCE_UNIT_ALERT_TARGET_TIME 3
