/// @description Shared unit information used by the battle HUD and world map.
function hud_unit_base_stats_get(_unit_object)
{
	var _stats = noone;

	if (_unit_object == o_skeleton_bonelet)
	{
		_stats = hud_unit_base_stats_create(BALANCE_SKELETON_BONELET_HP, BALANCE_SKELETON_BONELET_ARMOR, BALANCE_SKELETON_BONELET_MAGIC_RESISTANCE, BALANCE_SKELETON_BONELET_DAMAGE, 0, BALANCE_SKELETON_BONELET_RELOAD_TIME, BALANCE_SKELETON_BONELET_ATTACK_RADIUS, BALANCE_SKELETON_BONELET_MOVE_SPEED);
	}
	else if (_unit_object == o_skeleton_warrior)
	{
		_stats = hud_unit_base_stats_create(BALANCE_SKELETON_WARRIOR_HP, BALANCE_SKELETON_WARRIOR_ARMOR, BALANCE_SKELETON_WARRIOR_MAGIC_RESISTANCE, BALANCE_SKELETON_WARRIOR_DAMAGE, 0, BALANCE_SKELETON_WARRIOR_RELOAD_TIME, BALANCE_SKELETON_WARRIOR_ATTACK_RADIUS, BALANCE_SKELETON_WARRIOR_MOVE_SPEED);
	}
	else if (_unit_object == o_skeleton_archer)
	{
		_stats = hud_unit_base_stats_create(BALANCE_SKELETON_ARCHER_HP, BALANCE_SKELETON_ARCHER_ARMOR, BALANCE_SKELETON_ARCHER_MAGIC_RESISTANCE, BALANCE_SKELETON_ARCHER_DAMAGE, 0, BALANCE_SKELETON_ARCHER_RELOAD_TIME, BALANCE_SKELETON_ARCHER_ATTACK_RADIUS, BALANCE_SKELETON_ARCHER_MOVE_SPEED);
	}
	else if (_unit_object == o_skeleton_mage)
	{
		_stats = hud_unit_base_stats_create(BALANCE_SKELETON_MAGE_HP, BALANCE_SKELETON_MAGE_ARMOR, BALANCE_SKELETON_MAGE_MAGIC_RESISTANCE, 0, BALANCE_SKELETON_MAGE_MAGIC_DAMAGE, BALANCE_SKELETON_MAGE_RELOAD_TIME, BALANCE_SKELETON_MAGE_ATTACK_RADIUS, BALANCE_SKELETON_MAGE_MOVE_SPEED);
	}
	else if (_unit_object == o_skeleton_healer)
	{
		_stats = hud_unit_base_stats_create(BALANCE_SKELETON_HEALER_HP, BALANCE_SKELETON_HEALER_ARMOR, BALANCE_SKELETON_HEALER_MAGIC_RESISTANCE, BALANCE_SKELETON_HEALER_DAMAGE, BALANCE_SKELETON_HEALER_MAGIC_DAMAGE, BALANCE_SKELETON_HEALER_RELOAD_TIME, BALANCE_SKELETON_HEALER_ATTACK_RADIUS, BALANCE_SKELETON_HEALER_MOVE_SPEED);
	}
	else if (_unit_object == o_skeleton)
	{
		_stats = hud_unit_base_stats_create(BALANCE_SKELETON_HP, BALANCE_SKELETON_ARMOR, BALANCE_SKELETON_MAGIC_RESISTANCE, BALANCE_SKELETON_DAMAGE, 0, BALANCE_SKELETON_RELOAD_TIME, BALANCE_SKELETON_ATTACK_RADIUS, BALANCE_SKELETON_MOVE_SPEED);
	}
	else if (_unit_object == o_ripcage_cannon)
	{
		_stats = hud_unit_base_stats_create(BALANCE_RIPCAGE_CANNON_HP, BALANCE_RIPCAGE_CANNON_ARMOR, BALANCE_RIPCAGE_CANNON_MAGIC_RESISTANCE, BALANCE_RIPCAGE_CANNON_DAMAGE, 0, BALANCE_RIPCAGE_CANNON_RELOAD_TIME, BALANCE_RIPCAGE_CANNON_ATTACK_RADIUS, BALANCE_RIPCAGE_CANNON_MOVE_SPEED);
	}
	else if (_unit_object == o_bone_bannerman)
	{
		_stats = hud_unit_base_stats_create(BALANCE_BONE_BANNERMAN_HP, BALANCE_BONE_BANNERMAN_ARMOR, BALANCE_BONE_BANNERMAN_MAGIC_RESISTANCE, BALANCE_BONE_BANNERMAN_DAMAGE, BALANCE_BONE_BANNERMAN_MAGIC_DAMAGE, BALANCE_BONE_BANNERMAN_RELOAD_TIME, BALANCE_BONE_BANNERMAN_ATTACK_RADIUS, BALANCE_BONE_BANNERMAN_MOVE_SPEED);
	}
	else if (_unit_object == o_provocateur)
	{
		_stats = hud_unit_base_stats_create(BALANCE_PROVOCATEUR_HP, BALANCE_PROVOCATEUR_ARMOR, BALANCE_PROVOCATEUR_MAGIC_RESISTANCE, BALANCE_PROVOCATEUR_DAMAGE, BALANCE_PROVOCATEUR_MAGIC_DAMAGE, BALANCE_PROVOCATEUR_RELOAD_TIME, BALANCE_PROVOCATEUR_ATTACK_RADIUS, BALANCE_PROVOCATEUR_MOVE_SPEED);
	}
	else if (_unit_object == o_mawling)
	{
		_stats = hud_unit_base_stats_create(BALANCE_MAWLING_HP, BALANCE_MAWLING_ARMOR, BALANCE_MAWLING_MAGIC_RESISTANCE, BALANCE_MAWLING_DAMAGE, 0, BALANCE_MAWLING_RELOAD_TIME, BALANCE_MAWLING_ATTACK_RADIUS, BALANCE_MAWLING_MOVE_SPEED);
	}
	else if (_unit_object == o_pitling)
	{
		_stats = hud_unit_base_stats_create(BALANCE_PITLING_HP, BALANCE_PITLING_ARMOR, BALANCE_PITLING_MAGIC_RESISTANCE, BALANCE_PITLING_DAMAGE, 0, BALANCE_PITLING_RELOAD_TIME, BALANCE_PITLING_ATTACK_RADIUS, BALANCE_PITLING_MOVE_SPEED);
	}
	else if (_unit_object == o_succubus)
	{
		_stats = hud_unit_base_stats_create(BALANCE_SUCCUBUS_HP, BALANCE_SUCCUBUS_ARMOR, BALANCE_SUCCUBUS_MAGIC_RESISTANCE, BALANCE_SUCCUBUS_DAMAGE, BALANCE_SUCCUBUS_MAGIC_DAMAGE, BALANCE_SUCCUBUS_RELOAD_TIME, BALANCE_SUCCUBUS_ATTACK_RADIUS, BALANCE_SUCCUBUS_MOVE_SPEED);
	}
	else if (_unit_object == o_balgor)
	{
		_stats = hud_unit_base_stats_create(BALANCE_BALGOR_HP, BALANCE_BALGOR_ARMOR, BALANCE_BALGOR_MAGIC_RESISTANCE, BALANCE_BALGOR_DAMAGE, 0, BALANCE_BALGOR_RELOAD_TIME, BALANCE_BALGOR_ATTACK_RADIUS, BALANCE_BALGOR_MOVE_SPEED);
	}
	else if (_unit_object == o_demon_wizard)
	{
		_stats = hud_unit_base_stats_create(BALANCE_DEMON_WIZARD_HP, BALANCE_DEMON_WIZARD_ARMOR, BALANCE_DEMON_WIZARD_MAGIC_RESISTANCE, BALANCE_DEMON_WIZARD_DAMAGE, BALANCE_DEMON_WIZARD_MAGIC_DAMAGE, BALANCE_DEMON_WIZARD_RELOAD_TIME, BALANCE_DEMON_WIZARD_ATTACK_RADIUS, BALANCE_DEMON_WIZARD_MOVE_SPEED);
	}
	else if (_unit_object == o_imp)
	{
		_stats = hud_unit_base_stats_create(BALANCE_IMP_HP, BALANCE_IMP_ARMOR, BALANCE_IMP_RESISTANCE, BALANCE_IMP_DAMAGE, 0, 1 / BALANCE_IMP_ATTACK_SPEED, BALANCE_IMP_ATTACK_RADIUS, BALANCE_IMP_MOVE_SPEED);
	}
	else if (_unit_object == o_brute)
	{
		_stats = hud_unit_base_stats_create(BALANCE_BRUTE_HP, BALANCE_BRUTE_ARMOR, BALANCE_BRUTE_RESISTANCE, BALANCE_BRUTE_DAMAGE, 0, 1 / BALANCE_BRUTE_ATTACK_SPEED, BALANCE_BRUTE_ATTACK_RADIUS, BALANCE_BRUTE_MOVE_SPEED);
	}
	else if (_unit_object == o_warlock)
	{
		_stats = hud_unit_base_stats_create(BALANCE_WARLOCK_HP, BALANCE_WARLOCK_ARMOR, BALANCE_WARLOCK_RESISTANCE, 0, BALANCE_WARLOCK_MAGIC_DAMAGE, 1 / BALANCE_WARLOCK_ATTACK_SPEED, BALANCE_WARLOCK_ATTACK_RADIUS, BALANCE_WARLOCK_MOVE_SPEED);
	}

	return _stats;
}
